service: serverless-backstopjs

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 2048
  timeout: 30
  apiGateway:
    apiKeys:
      - serverless-backstopjs-key-dev

package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**
    - node_modules/aws-sdk/**

plugins:
  - serverless-offline

functions:
  serverless-backstopjs-fn:
    handler: handler.index
    events:
      - http:
          path: /serverless-backstopjs
          method: post
